type Query {
  signin(email: String!, password: String!): String!
  user(userId: ID): User
}

type Mutation {
  signup(user: UserInput!): String!
  addFeedBook(isbn: String!, comment: String!, date: String!): UserFeedBook!
}

type User {
  _id: ID!
  email: String!
  name: String!
  feedBooks: [UserFeedBook!]!
}

type UserFeedBook {
  book: Book!
  comment: String!
  date: String!
}

input UserInput {
  email: String!
  name: String!
  password: String!
}

type Book {
  isbn: String!
  title: String!
  subTitle: String
  description: String
  authors: [String!]
  pages: Int
  publisher: String
  published: String
  thumbnail: String
}
