type Query {
  signin(email: String!, password: String!): String!
  user(userId: ID): User
  book(bookId: String!): Book
  bookQuery(query: String!): [Book!]!
}

type Mutation {
  signup(user: SignUpInput!): String!
  addFeedBook(bookId: String!, comment: String!, date: String!): UserFeedBook!
  removeFeedBook(_id: ID!): UserFeedBook!
}

type User {
  _id: ID!
  email: String!
  name: String!
  feedBooks(bookId: String): [UserFeedBook!]!
  profilePicture: File
}

type UserFeedBook {
  _id: ID!
  bookId: String!
  book: Book!
  comment: String!
  date: String!
}

input SignUpInput {
  email: String!
  name: String!
  password: String!
}

input UserUpdateInput {
  email: String
  name: String
  password: String
  profilepicture: Upload
}

type Book {
  bookId: String!
  title: String!
  subTitle: String
  description: String
  authors: [String!]
  pages: Int
  publisher: String
  published: String
  thumbnail: String
}
